In [3]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(10)
a1 + a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
[x+y for x in range(10) for y in range(10) ]  #it take 1 element of x and add with all element of

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18]

In [5]:
l1 = list(range(10))
l2 = list(range(10))
[x+y for x,y in list(zip(l1,l2)) ]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
import numpy as np
a = np.array([1,2])

In [7]:
a

array([1, 2])

In [8]:
a.size  #size i.e 2 elements

2

In [9]:
a.ndim #dimension

1

In [10]:
a.shape

(2,)

In [16]:
a.itemsize

8

In [23]:
a = np.array([[1,2,3],[3,4,5]])

In [24]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [25]:
a.shape

(2, 3)

In [26]:
a.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [27]:
a.dtype

dtype('int64')

In [29]:
b = np.array([[1,2,3],[3,4,5]],dtype='float')

In [30]:
b

array([[1., 2., 3.],
       [3., 4., 5.]])

In [52]:
b.ravel() #1d

array([1., 2., 3., 3., 4., 5.])

In [22]:
b.flatten()

array([1., 2., 3., 3., 4., 5.])

In [54]:
b.size

6

In [53]:
b.max()

5.0

In [55]:
b.min()

1.0

In [56]:
b.sum()

18.0

In [57]:
b.sum(axis=0) # sum of column

array([4., 6., 8.])

In [58]:
b.sum(axis=1)#sum of rows

array([ 6., 12.])

In [31]:
b.itemsize

8

In [59]:
np.sum(b)

18.0

In [31]:
b.ndim

2

In [35]:
c=np.zeros((3,4))

In [37]:
c

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [36]:
c=np.full((3,3), 8)

In [33]:
c=np.ones((3,3))

In [48]:
np.arange(1,5)  #array start form 1 to 4

array([1, 2, 3, 4])

In [63]:
np.arange(1,5,2) #1 to 5 with step 2

array([1, 3])

In [47]:
np.linspace(1,5,10)  #from 1 to 5 ---- 10 nos

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
b

array([[1., 2., 3.],
       [3., 4., 5.]])

In [62]:
print(b.T)#transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

[[1. 3.]
 [2. 4.]
 [3. 5.]]


In [38]:
d = np.empty_like(c)   # Create an empty matrix with the same shape as c


In [39]:
c.size

9

In [40]:
d.size

9

In [41]:
c.shape

(3, 3)

In [42]:
d.shape

(3, 3)

In [43]:
type(d)

numpy.ndarray

In [44]:
d = np.full((3, 3), 6, dtype = 'int')


In [45]:
d

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [76]:
a

array([1, 2])

In [77]:
b

array([[1., 2., 3.],
       [3., 4., 5.]])

In [53]:
b = np.array([[1,2,7,1],[1,3,4,8],[1,5,6,9],[1,7,8,9]])

In [61]:
b

array([[1, 2, 7, 1],
       [1, 3, 4, 8],
       [1, 5, 6, 9],
       [1, 7, 8, 9]])

In [64]:
b[:,::3] #all rows n 0,3 column

array([[1, 1],
       [1, 8],
       [1, 9],
       [1, 9]])

In [66]:
b[:,::1] #everything

array([[1, 2, 7, 1],
       [1, 3, 4, 8],
       [1, 5, 6, 9],
       [1, 7, 8, 9]])

In [67]:
b[:,::2]#all row n o,2 cloumn

array([[1, 7],
       [1, 4],
       [1, 6],
       [1, 8]])

In [68]:
b[:,1:]

array([[2, 7, 1],
       [3, 4, 8],
       [5, 6, 9],
       [7, 8, 9]])

In [83]:
b[-1,-1]

9

In [70]:
for i in b:
    print (i)

[1 2 7 1]
[1 3 4 8]
[1 5 6 9]
[1 7 8 9]


In [86]:
for i in b.flat:
    print(i)

1
2
7
3
4
8
5
6
9


In [71]:
for i in b.flatten():
    print(i)

1
2
7
1
1
3
4
8
1
5
6
9
1
7
8
9


In [88]:
b.ravel()

array([1, 2, 7, 3, 4, 8, 5, 6, 9])